apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: error-rate
    interval: 2m
    successCondition: result <= 1
    failureLimit: 1
    provider:
      datadog:
        interval: 2m
        query: |
          default_zero(sum:trace.express.request.hits.by_http_status{http.status_class:5xx,service:account-api})