apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: error-rate
    interval: 30s
    successCondition: result <= 5
    failureLimit: 1
    provider:
      datadog:
        interval: 30s
        query: |
          sum:trace.express.requests.hits.by_http_status{http.status_code:404,service:{{args.service-name}}}