apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: error-rate
    interval: 5m
    successCondition: result <= 2
    failureLimit: 3
    provider:
      datadog:
        interval: 5m
        query: |
          sum:trace.express.requests.hits.by_http_status{http.status_code:404,service:{{args.service-name}}}