apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-api
  labels:
    app: account-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: account-api
    spec:
      containers:
      - image: maxday/account-api:latest
        imagePullPolicy: Always
        name: account-api
        ports:
        - containerPort: 3000
          protocol: TCP
