name: 'Run tests, dockerize and publish'
on:
  push:
    branches-ignore:
      - dependabot

jobs:
  publish:
    name: Run tests, dockerize and publish
    runs-on: ubuntu-latest
    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Test
        run: npm test
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: maxday
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push docker
        run: | 
          PACKAGE_VERSION=$(cat ./package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          docker build --build-arg AUTH_TOKEN=${AUTH_TOKEN} -t maxday/account-api:${PACKAGE_VERSION}-${GITHUB_SHA} .
          docker push maxday/account-api:${PACKAGE_VERSION}-${GITHUB_SHA}
          sed "s/___VERSION___/${PACKAGE_VERSION}-${GITHUB_SHA}/g" k8s/rollout.yaml.tpl > k8s/rollout.yaml
      - name: Commit files
        run: |
          git config --local user.email "github-actions-bot@maximedavid.fr"
          git config --local user.name "github-actions-bot"
          git add k8s/rollout.yaml
          git commit -m "Update version in deployment file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main