name: 'Run tests'
on:
  push:
    
jobs:
  publish:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Test
        run: npm test