name: 'Run tests, dockerize and publish'
on:
  push:
    
jobs:
  publish:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Test
        run: npm test
      - name: Build docker
        run: | 
          PACKAGE_VERSION=$(cat ./package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          docker build --build-arg AUTH_TOKEN=${AUTH_TOKEN} -t maxday/account-api:${PACKAGE_VERSION} .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: maxday
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to docker
        run: docker push maxday/account-api:${PACKAGE_VERSION}